//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalDressesEntities1 : DbContext
    {
        public RentalDressesEntities1()
            : base("name=RentalDressesEntities1")
        {
        }

      
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<User>().ToTable("User");
        }

        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Dresses> Dresses { get; set; }
        public virtual DbSet<Rentals> Rentals { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
